# Generated by Django 5.2.3 on 2025-07-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_matricula_costo_alter_estudiante_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='costo_matricula',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
    ]
